CREATE TABLE driver_profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    license_number VARCHAR(100) UNIQUE NOT NULL,
    vehicle_model VARCHAR(120) NOT NULL,
    vehicle_plate_number VARCHAR(40) UNIQUE NOT NULL,
    vehicle_color VARCHAR(60) NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    rating DECIMAL(3, 2) NOT NULL DEFAULT 5.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
